### ISSUE TITLE
Feature request: get slice covered by index

### ISSUE THREAD

**Issue by daisylb** [gahaalt/slicemap#3]
Hi! Thanks so much for this package, it's really useful!

A feature that I think it would be really useful to add is the ability to get the slice that is covered by a particular index. For example:

```py
>>> slicemap
{(-inf,0): None, [0,3): a, [3,6): b, [6,9): c, [9,inf): None}
>>> slicemap.get_slice_at(5)
(3, 6, 'b')
```

The current application I'm using slicemap for is this: I have a HTML document tree, and I need to process it as a string (using `re.search`). So I'm converting it to a string manually, and using `slicemap` to track which parts of the string map to which nodes of the original tree.

As part of what I'm doing, I need to be able to get the text that appears between the start of the DOM node and the start of the regex match. So with this feature, my code might look like this:

```py
node_start_offset, node_end_offset, node = slicemap.get_slice_at(match.start())
node_contents_before_match = text[node_start_offset:match.start()]
```

**Comment by szmikler** [comment]
Hey! Thanks for using slicemap, I am glad it was useful!

I added the requested feature, you can use `get_slice_at` in version 1.1.2 of the package. It returns a namedtuple instead of a tuple, but you can still unpack it like in your example.

Screenshot from updated docs:
![obraz](https://github.com/sjmikler/slicemap/assets/43541355/b293dae7-69a9-4661-a09c-de18502787c5)

Feel free to reopen the issue if you need!
